src/module/dialogs/combat/CombatDefenseDialog.ts
Fixes #73 
La solución permite mantener la UI tal y como estaba, mostrando los penalizadores en negativo y la fórmula del chat sin concatenar símbolos de + y -.
=> Fix multiple defenses penalizer adding instead of substracting

distributionconfig.json, foundryconfig.example.json, gulpfile.js
Esta PR extrae la configuración de publicación a un archivo estático que sí está incluído en control de versiones, de manera que sea más difícil cambiar el repositorio al generar una nueva release.
=> Extract distribution config to separate file

src/module/dialogs/combat/GMCombatDialog.ts
Now fatigue is no longer modified when showing combat results on chat.
=> Solves #104: fatigue is no longer modified when showing combat results

src/module/actor/utils/prepareActor/calculations/actor/domine/mutateDomineData.ts, src/module/actor/utils/prepareActor/prepareActor.ts
In order to fix #89 and calculate final values for ki accumulations a `mutateDomineData` function has been created and added to `prepareActor`.
=> Add mutateDomineData for calculating final values for ki accumulations

package-lock.json, package.json, src/module/actor/ABFActorSheet.ts, src/module/dialogs/GenericDialog.ts, src/module/dialogs/combat/CombatAttackDialog.ts, src/module/dialogs/combat/CombatDefenseDialog.ts, src/module/dialogs/combat/GMCombatDialog.ts, src/module/items/ABFItemSheet.ts, src/module/macros/functions/damageCalculatorMacro.ts, src/module/types/Items.ts, src/scss/actor/parts/main.scss, src/system.json, src/templates/actor/actor-sheet.hbs, src/templates/actor/parts/general/general.hbs, src/templates/actor/parts/mystic/mystic.hbs, src/templates/actor/parts/psychic/psychic.hbs, src/templates/dialog/combat/combat-attack/combat-attack-dialog.hbs, src/templates/dialog/combat/combat-defense/combat-defense-dialog.hbs
Finally, I found some time to migrate the types of Foundry VTT 9. Here it is.
Some change notes:
- For some reason, Foundry doesn't maintain the support of the tabs style, so I have to re-write some style code, not a big deal.
- The damage calculator was the "big" change. I said "big" because was just a few lines of code.
I tested in my current campaign world and everything works fine.
=> Migrate types to v9

src/module/dialogs/combat/GMCombatDialog.ts
When combat results were sent to the chat, enemies' info like name and image was shown instead of the token that actually is doing the attack.
In this PR token name and image is used instead.
=> [Changes] Hide attacker and defender internal data

src/module/combat/ABFCombat.ts
This is related with #105, which was supposed to fix this bug. Now we set manually the active combatant after rolling initiative, so that it makes active the player with higher initiative after rolling at the beginning of each round.
We use a boolean flag `newRound`, whose value is mantained by `nextRound()` and `nextTurn()`, to indicate whether we are at the beginning of the round or not.
=> Fix bug on setting the current combatant after rolling initiative

src/module/actor/utils/prepareActor/calculations/actor/mutateTotalArmor.ts
Fixes #148.
The problem was caused because of `.sort()` method of arrays not ordering numbers as numbers but _alphabetically_ which caused 12 to be _smaller_ than 4 since 1 goes before 4. Using typed arrays solved the issue since `Int8Array` (and all the int arrays) does sort integers correctly.
=> Fix combined armor

src/module/types/ABFItemConfig.js
Now `.addToFieldPath()` looks for the current item inside the array of items of that type and updates the old by the new one if exists or pushes it otherwise. Therefore the order of items of a subtype does not change when preparing items.
=> Fix #167: inner items do not reorder when updating them anymore

src/scss/actor/parts/general.scss, src/templates/actor/parts/general/parts/language.hbs, src/templates/actor/parts/general/parts/level.hbs, src/utils/handlebars-helpers/helpers/calculateLanguagesHBSHelper.js, src/utils/handlebars-helpers/helpers/calculateLevelsHBSHelper.js, src/utils/handlebars-helpers/registerHelpers.ts
Fixes #169.
- The max amount of languages a character can learn has been calculated following the excel sheet table, and is now displayed on the title of languages part in the actor sheet.
- The total level is calculated adding up the values on each of the categories and is displayed on the title of categories part on the actor sheet.
=> Maximum amount of languages and total level in category

src/module/actor/utils/prepareActor/prepareActor.js
El problema con el cálculo del penalizador de movimiento por armadura, es que primero se está calculando el movimiento antes de haber calculado la armadura.
En este fix solo se cambia el orden de los mutateData para que funcione correctamente.
=> fix - mutateMovementType order

.github/ISSUE_TEMPLATE/bug-report-------.md, .github/ISSUE_TEMPLATE/new-suggestion-------.md, .github/ISSUE_TEMPLATE/nueva-sugerencia-------.md, .github/ISSUE_TEMPLATE/reportar-bug-------.md, .github/workflows/main.yml, scripts/release/release.js
The release script allows now to introduce a new version number (and will update with it both package.json and system.json), and will auto-create the github release (auto-uploading attachments) if gh CLI command is present and configured.
It also removes the flags from issue templates (this was causing an issue with `gh dash`).
=> Improve release script

src/module/migration/migrations/6-fix-old-modifiers.js, src/module/migration/migrations/7-fix-weapons-ownStrength.js, src/module/migration/migrations/8-remove-unused-weaponFue.js, src/module/migration/migrations/index.js, src/template.json
Faltaban nuevos datos de las armas en el archivo template (`isShield`, `equipped` y `hasOwnStr`).
En ``calculateWeaponStrengthModifier`` agregué un ``?``  en ``if (weapon.system.hasOwnStr?.value)`` ya que me daba error de consola por algún arma que no se inicializó con el dato nuevo.
=> fix - weapon template hasOwnStr

src/module/actor/utils/prepareActor/calculations/actor/general/mutateMovementType.js
Esta PR corrige un error en el cálculo de los penalizadores al tipo de movimiento.
El código estaba usando `Math.floor()` (y al ser números negativos el penalizador se aplicaba antes de llegar al número necesario).
fixes #197 
Se ha verificado que el cálculo del TM se ajusta correctamente según los nuevos criterios de penalización.
<details><summary>Evidencias - SIN Fix</summary>
<p>
</p>
</details> 
<details><summary>Evidencias - CON Fix</summary>
<p>
</p>
</details>
=> FIX - El tipo de movimiento debe reducirse solo en multiplos de 20

src/module/actor/utils/prepareActor/calculations/actor/modifiers/calculations/calculateArmorPhysicalPenalty.js
Esta PR corrige un error en el calculo de los penalizadores de penalizadores de Armaduras, en el caso de tener un valor negativo los penalizadores se aplicaban incluso si no llevaras armadura, se ha añadido un if statement que comprueba si llevas armaduras, si no es el caso el penalizador es siempre 0
fixes #203
Se ha verificado que con valores negativos (y positivos) de armadura los penalizadores se aplican cuando es pertinente.
<details><summary>Evidencias - SIN Fix</summary>
<p>
</p>
</details> 
<details><summary>Evidencias - CON Fix</summary>
<p>
</p>
</details>
=> FIX - Los penalizadores de armadura deben aplicarse solo cuando hay una armadura equipada

src/lang/en.json, src/lang/es.json, src/lang/fr.json, src/templates/actor/parts/domine/parts/seals.hbs
Esta PR ajusta los sellos del KI a lo estipulado en el Manual.
Se ha añadido el sello de fuego y se ha eliminado el de Tierra dejando en su lugar el de madera.
fixes #205
Se ha verificado que los nuevos sellos funcionan y se muestran en la ficha
<details><summary>Evidencias - CON Fix</summary>
<p>
</p>
=> FIX - Añadido el Sello de fuego y eliminado el sello de Tierra

src/packs/psychic_powers/psychicPower_Destrozar_qZYLb8n1LaMnncLs.json
Se ha modificado el poder Destrozar para que ponga lo mismo que el manual, en losefectos a partir de muy dificil se debe resistir con Resistencia Física y no Psíquica como ponía antes.
fixes #227
<details><summary>Evidencias</summary>
<p>
</p>
</details>
=> FIX - El poder Psiquico Destrozar usa RF en vez de RP

src/module/actor/ABFActorSheet.js
Al lanzarse un `.update(...)` de los actores de tokens no linkeados, foundry estaba ejecutando un render (con `force=false`, por lo que en principio solo se actualizan fichas ya abiertas y no se abre ninguna nueva) de las fichas de los mismos (ver imagen). 
Por la anterior implementación (en #213), como el método `_canUserView()` se llama siempre al pasar por `sheet._render()` antes de comprobar el valor de `force`, eso estaba abriendo las imágenes en estos casos para todos los jugadores que no podían ver las fichas de los tokens no linkeados.
Ahora se abre el popout de la imagen desde la función `_render(...)`, sólo si es llamada con `force=true` y sólo si el usuario tiene exactamente el permiso `LIMITED` (antes se comprobaba que tuviese permiso _menor o igual_ que `LIMITED`).
También, …
=> Fix: image popout spam when GM updating base actor for unlinked tokens

docs/develop/es/es.md, docs/develop/es/foundry-cli.md, scripts/copyDirectoryToFoundrySystem.js
En #214 se incluyó el uso de foundryvtt-cli para gestionar los compendios. Trasteando he visto que puede ser útil usarlo también para tener varias versiones de foundry instaladas y poder cambiar "fácilmente" entre ellas. Al empezar a usarlo, he visto que tiene sentido extraer el path de la instalación de ahí si fvtt está instalado.
He modificado el script que copia la build a la carpeta de datos de foundry para obtener del cli la ubicación de dicha carpeta si éste está instalado (globalmente). En caso de que no esté instalado globalmente, lo ignora y usa el `destPath` que se encuentra en `foundryconfig.json`.
También he creado documentación (incluyendo el código para un script útil) explicando cómo cambiar el flujo de trabajo para usar el CLI para gestionar las versiones instaladas de …
=> Use foundryvtt-cli to get the build destination path

src/module/actor/ABFActor.js, src/module/types/combat/SupernaturalShieldItemConfig.js, src/module/types/mystic/SpellItemConfig.js
> [!WARNING]
> BREAKS (old) combat dialogs in main. This PR can only be merged together with new svelte combat.
This PR breaks combat dialogs, since they used the (old) removed methods. This is unimportant since we are completely rewriting the dialogs with the new svelte approach, and there we use the new methods.
We introduce two new methods, `actor.canCastSpell(spell, spellGrade, castMethod, increasedCost = { zeon: 0, pool: 0 })` and `castSpell(spell, spellGrade, castMethod, increasedCost = { zeon: 0, pool: 0 })`.
- `.canCastSpell(...)` is responsible for checking if the actor can cast the given spell at a particular `spellGrade` using a given `casMethod`, notifying the user if this is not the case.
- `.casSpell(...)` delegates in `canCastSpell(...)` to check if the actor can cast the …
=> Simplify logic for spellcasting methods in actor.
